baseURL = 'https://loot.github.io/'
languageCode = 'en-us'
title = 'LOOT'

[outputs]
  home = ['html']
  page = ['html']
  rss = ['rss']
  section = ['html']
  taxonomy = []
  term = []

[module]
  [[module.mounts]]
    disableWatch = false
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'node_modules/material-design-lite'
    target = 'assets/material-design-lite'
